import { generateText } from "ai";
import { createGroq } from "@ai-sdk/groq";
import { prisma as defaultPrisma } from "../config/db.js";

// Every function here takes its dependencies through a trailing options object
// that defaults to the real client, the same shape controller/chatTools.js uses.
// Production callers pass nothing; tests pass doubles. Nothing in this file
// reaches for a dependency on its own, so a test never needs a live database.

// A conversation title is only ever a label in the sidebar, so it is taken from
// the first thing the user typed rather than generated by a model. Creating a
// conversation stays one cheap insert with no extra API call.
const MAX_TITLE_LENGTH = 60;

function buildTitle(firstMessage) {
  if (!firstMessage) return null;
  const trimmed = firstMessage.trim();
  return trimmed.length <= MAX_TITLE_LENGTH
    ? trimmed
    : `${trimmed.slice(0, MAX_TITLE_LENGTH - 1)}…`;
}

/**
 * Find the conversation this request belongs to, or start a new one.
 *
 * No conversationId means the user just opened a fresh chat.
 *
 * When an id is supplied we look it up by id *and* userId together. Looking up
 * by id alone would let anyone read someone else's chat just by guessing or
 * stealing an id. A miss is reported as 404 rather than 403 even when the row
 * exists but belongs to another user: a 403 would confirm that the id is real,
 * which is information an attacker should not get.
 */
export async function getOrCreateConversation(
  userId,
  conversationId,
  firstMessage,
  { prisma = defaultPrisma } = {},
) {
  if (!conversationId) {
    return prisma.conversation.create({
      data: { userId, title: buildTitle(firstMessage) },
    });
  }

  const conversation = await prisma.conversation.findFirst({
    where: { id: conversationId, userId },
  });

  if (!conversation) {
    const error = new Error("Conversation not found");
    error.statusCode = 404;
    throw error;
  }

  return conversation;
}

// A sidebar is a glance, not an archive. Capping the query keeps it one small
// indexed read however many threads a user accumulates.
const CONVERSATION_LIST_LIMIT = 30;

/**
 * The user's most recently active conversations, newest first.
 *
 * Ordering by updatedAt rather than createdAt puts a thread the user has just
 * replied in at the top, which is what "recent" means to them. appendMessage
 * bumps updatedAt on every turn, and the @@index([userId, updatedAt]) on
 * Conversation is what makes this a cheap read.
 *
 * Returns no message bodies: the list only needs a label per row.
 */
export async function listConversations(userId, { prisma = defaultPrisma } = {}) {
  return prisma.conversation.findMany({
    where: { userId },
    orderBy: { updatedAt: "desc" },
    take: CONVERSATION_LIST_LIMIT,
    select: { id: true, title: true, updatedAt: true },
  });
}

/**
 * Messages in the conversation, oldest first.
 *
 * `fromSeq` skips everything already folded into the rolling summary, which is
 * what keeps the prompt from growing without limit. Omit it to get the whole
 * thread, which is what the UI wants: a reader should see every message, even
 * the ones the model is now being given as a summary instead.
 */
export async function loadHistory(conversationId, { fromSeq, prisma = defaultPrisma } = {}) {
  return prisma.chatMessage.findMany({
    where: {
      conversationId,
      ...(fromSeq ? { seq: { gte: fromSeq } } : {}),
    },
    orderBy: { seq: "asc" },
  });
}

/**
 * Append one message to a conversation.
 *
 * seq is "the highest one so far, plus one", which is a read followed by a
 * write. Two requests running at once could both read the same highest value
 * and then both try to insert it, and the second would be rejected by the
 * unique constraint on (conversationId, seq).
 *
 * Updating the parent Conversation row first is what prevents that. Postgres
 * holds a lock on an updated row until the surrounding transaction commits, so
 * a second append to the same conversation waits at that line instead of racing
 * us. The row has to be touched anyway to bump updatedAt for the sidebar
 * ordering, so the lock costs nothing extra.
 */
export async function appendMessage(
  conversationId,
  { role, content, movies },
  { prisma = defaultPrisma } = {},
) {
  return prisma.$transaction(async (tx) => {
    await tx.conversation.update({
      where: { id: conversationId },
      data: { updatedAt: new Date() },
    });

    const last = await tx.chatMessage.findFirst({
      where: { conversationId },
      orderBy: { seq: "desc" },
      select: { seq: true },
    });

    return tx.chatMessage.create({
      data: {
        conversationId,
        role,
        content,
        // undefined omits the column so it stays SQL NULL. Passing null here
        // would ask Prisma to store the JSON value `null`, which is different.
        movies: movies ?? undefined,
        seq: last ? last.seq + 1 : 0,
      },
    });
  });
}

/**
 * Reshape stored rows into the {role, content} pairs the AI SDK expects,
 * dropping the columns it has no use for and lowercasing the enum.
 *
 * Kept pure — no database, no network, same output for the same input — so it
 * can be unit tested directly. Logic buried inside the controller's chat()
 * cannot be, which is why test/chatTools.test.js has to reimplement the tools
 * it wants to check.
 */
export function buildModelMessages(rows) {
  return rows.map((row) => ({
    role: row.role === "USER" ? "user" : "assistant",
    content: row.content,
  }));
}

/**
 * Reshape stored rows for the browser.
 *
 * Deliberately not the same as buildModelMessages. The UI needs the row id to
 * use as a React key and the movie cards to render, while the model is sent
 * neither: ids mean nothing to it, and the card details are already in the text
 * it wrote. Merging the two would push wasted tokens into every request.
 */
export function buildClientMessages(rows) {
  return rows.map((row) => ({
    id: row.id,
    role: row.role === "USER" ? "user" : "assistant",
    content: row.content,
    movies: row.movies ?? undefined,
  }));
}

// How many of the most recent messages always stay word for word. Five turns is
// enough for "the second one", "that other film", "make it shorter" to resolve
// against the actual text rather than a paraphrase of it.
const KEEP_RECENT = 10;

// How far past the window a conversation must drift before it is worth folding.
// Summarising the instant a single message falls out would mean an extra model
// call on nearly every turn to compress one message.
const SUMMARY_TRIGGER = 6;

/**
 * The default compressor: one call to a small model.
 *
 * Separated from maybeSummarize so the watermark arithmetic can be tested
 * without a network call, and so swapping the model or the wording never means
 * touching the logic that decides what to fold.
 */
async function summarizeWithModel({ previousSummary, transcript }) {
  // The small sibling of the chat model. This is compression, not reasoning, and
  // it runs on every long conversation, so it should not cost what answering
  // costs. (llama-3.1-8b-instant is not available on this Groq account.)
  const groq = createGroq({ apiKey: process.env.GROQ_API_KEY });

  const { text } = await generateText({
    model: groq("openai/gpt-oss-20b"),
    system:
      "You compress the older part of a film-recommendation chat so it can be " +
      "carried forward as context. Keep stated tastes, dislikes, constraints " +
      "such as runtime or cinema, films already suggested, and anything the " +
      "user said they had watched or rated. Drop pleasantries and repetition. " +
      "Write one compact paragraph of plain prose, no headings, no lists.",
    prompt: previousSummary
      ? `Summary of the conversation so far:\n${previousSummary}\n\nNewer messages to fold into it:\n${transcript}`
      : `Conversation to summarise:\n${transcript}`,
  });

  return text;
}

/**
 * Fold the oldest messages of a conversation into its rolling summary.
 *
 * Rolling, not re-summarised from scratch: each run is given the previous
 * summary plus only the messages that have newly fallen out of the window, so
 * the cost of a run stays flat no matter how long the conversation gets.
 *
 * Safe to run more than once, and safe to lose. summarizedUpTo is the seq where
 * unsummarised history begins, so a run only ever reads messages above it, and
 * the write below refuses to apply if another run moved the watermark first. A
 * run that never happens is simply picked up on the next turn.
 *
 * Call this after the response has been sent. It must never be on the path
 * between the model and the user.
 */
export async function maybeSummarize(
  conversationId,
  { prisma = defaultPrisma, summarize = summarizeWithModel } = {},
) {
  const conversation = await prisma.conversation.findUnique({
    where: { id: conversationId },
    select: { summary: true, summarizedUpTo: true },
  });
  if (!conversation) return { summarized: false, reason: "gone" };

  const rows = await loadHistory(conversationId, {
    fromSeq: conversation.summarizedUpTo,
    prisma,
  });

  if (rows.length <= KEEP_RECENT + SUMMARY_TRIGGER) {
    return { summarized: false, reason: "below_threshold" };
  }

  const toFold = rows.slice(0, rows.length - KEEP_RECENT);
  // Exclusive: the seq at which unsummarised history now begins.
  const nextWatermark = toFold[toFold.length - 1].seq + 1;

  const transcript = toFold
    .map((row) => `${row.role === "USER" ? "User" : "Assistant"}: ${row.content}`)
    .join("\n");

  const summary = (
    await summarize({ previousSummary: conversation.summary, transcript })
  ).trim();
  if (!summary) return { summarized: false, reason: "empty_summary" };

  // Conditional on the watermark we read. If a concurrent run already folded
  // these messages, this matches nothing and we discard our work rather than
  // overwriting a summary that is further ahead than ours.
  const { count } = await prisma.conversation.updateMany({
    where: { id: conversationId, summarizedUpTo: conversation.summarizedUpTo },
    data: { summary, summarizedUpTo: nextWatermark },
  });

  return count === 1
    ? { summarized: true, folded: toFold.length, summarizedUpTo: nextWatermark }
    : { summarized: false, reason: "raced" };
}
