import { prisma } from "../config/db.js";

// A conversation title is only ever a label in the sidebar, so it is taken from
// the first thing the user typed rather than generated by a model. Creating a
// conversation stays one cheap insert with no extra API call.
const MAX_TITLE_LENGTH = 60;

function buildTitle(firstMessage) {
  if (!firstMessage) return null;
  const trimmed = firstMessage.trim();
  return trimmed.length <= MAX_TITLE_LENGTH
    ? trimmed
    : `${trimmed.slice(0, MAX_TITLE_LENGTH - 1)}…`;
}

/**
 * Find the conversation this request belongs to, or start a new one.
 *
 * No conversationId means the user just opened a fresh chat.
 *
 * When an id is supplied we look it up by id *and* userId together. Looking up
 * by id alone would let anyone read someone else's chat just by guessing or
 * stealing an id. A miss is reported as 404 rather than 403 even when the row
 * exists but belongs to another user: a 403 would confirm that the id is real,
 * which is information an attacker should not get.
 */
export async function getOrCreateConversation(userId, conversationId, firstMessage) {
  if (!conversationId) {
    return prisma.conversation.create({
      data: { userId, title: buildTitle(firstMessage) },
    });
  }

  const conversation = await prisma.conversation.findFirst({
    where: { id: conversationId, userId },
  });

  if (!conversation) {
    const error = new Error("Conversation not found");
    error.statusCode = 404;
    throw error;
  }

  return conversation;
}

/** Every message in the conversation, oldest first. */
export async function loadHistory(conversationId) {
  return prisma.chatMessage.findMany({
    where: { conversationId },
    orderBy: { seq: "asc" },
  });
}

/**
 * Append one message to a conversation.
 *
 * seq is "the highest one so far, plus one", which is a read followed by a
 * write. Two requests running at once could both read the same highest value
 * and then both try to insert it, and the second would be rejected by the
 * unique constraint on (conversationId, seq).
 *
 * Updating the parent Conversation row first is what prevents that. Postgres
 * holds a lock on an updated row until the surrounding transaction commits, so
 * a second append to the same conversation waits at that line instead of racing
 * us. The row has to be touched anyway to bump updatedAt for the sidebar
 * ordering, so the lock costs nothing extra.
 */
export async function appendMessage(conversationId, { role, content, movies }) {
  return prisma.$transaction(async (tx) => {
    await tx.conversation.update({
      where: { id: conversationId },
      data: { updatedAt: new Date() },
    });

    const last = await tx.chatMessage.findFirst({
      where: { conversationId },
      orderBy: { seq: "desc" },
      select: { seq: true },
    });

    return tx.chatMessage.create({
      data: {
        conversationId,
        role,
        content,
        // undefined omits the column so it stays SQL NULL. Passing null here
        // would ask Prisma to store the JSON value `null`, which is different.
        movies: movies ?? undefined,
        seq: last ? last.seq + 1 : 0,
      },
    });
  });
}

/**
 * Reshape stored rows into the {role, content} pairs the AI SDK expects,
 * dropping the columns it has no use for and lowercasing the enum.
 *
 * Kept pure — no database, no network, same output for the same input — so it
 * can be unit tested directly. Logic buried inside the controller's chat()
 * cannot be, which is why test/chatTools.test.js has to reimplement the tools
 * it wants to check.
 */
export function buildModelMessages(rows) {
  return rows.map((row) => ({
    role: row.role === "USER" ? "user" : "assistant",
    content: row.content,
  }));
}

/**
 * Reshape stored rows for the browser.
 *
 * Deliberately not the same as buildModelMessages. The UI needs the row id to
 * use as a React key and the movie cards to render, while the model is sent
 * neither: ids mean nothing to it, and the card details are already in the text
 * it wrote. Merging the two would push wasted tokens into every request.
 */
export function buildClientMessages(rows) {
  return rows.map((row) => ({
    id: row.id,
    role: row.role === "USER" ? "user" : "assistant",
    content: row.content,
    movies: row.movies ?? undefined,
  }));
}
